# Generated by Django 5.2.13 on 2026-04-30 14:02

import game.engine
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_game_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('player_black_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_black_session', models.CharField(blank=True, max_length=40, null=True)),
                ('player_white_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_white_session', models.CharField(blank=True, max_length=40, null=True)),
                ('turn', models.CharField(default='black', max_length=10)),
                ('board_state', models.JSONField(default=game.engine.AbaloneEngine.get_initial_state)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
