# Generated by Django 5.2.13 on 2026-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
