# Generated by Django 5.2.13 on 2026-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rematch_requested_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_requested_white',
            field=models.BooleanField(default=False),
        ),
    ]
